name: aoc_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  colorize: ^3.0.0
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
